service: cart-service

plugins:
  - serverless-offline

package:
  patterns:
    - '!node_modules/**'

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action: dynamodb:*
          Resource: arn:aws:dynamodb:eu-central-1:744566837372:table/products

functions:
  main:
    handler: dist/src/main.handler
    events:
      - http:
          method: ANY
          path: /
          cors: true
      - http:
          method: ANY
          path: '{proxy+}'
          cors: true
